networks:
  app_network:
    external: true

services:
  payment-service:
    build: .
    container_name: payment-service
    ports:
      - "8002:8002"
    networks:
    - app_network
    depends_on:
      - mongo-db
    env_file:
      - .env
    restart: always

  mongo-db:
    image: mongo:8.0.4
    container_name: payment-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: master
      MONGO_INITDB_ROOT_PASSWORD: Sup3r5enh4
    ports:
      - "27017:27017"
    networks:
    - app_network
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all --auth

volumes:
  mongo_data:
