apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:1.0.0
          ports:
            - containerPort: 8002
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
            limits:
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: payment-service-config
          restartPolicy: Always
